[package]
name = "spherix-math"
version = "0.1.0"
edition = "2021"
authors = ["Bogdan Chertkov <d3lph1.contact@gmail.com>"]

[lib]

[dependencies]

spherix-util = {path = "../util"}

nalgebra = { workspace = true }
